version: '3.1'

services:
  api:
    build:
      context: ./api
    container_name: api-beers
    ports:
      - "80:5000"
    depends_on:
      - db
  db:
    build:
      context: ./sql
    container_name: db-beers
    environment:
      MYSQL_DATABASE: beer
      MYSQL_ROOT_PASSWORD: root